id: A2E5EC661
title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:42:37.471295
  last_modified_at: 2022-03-01 01:42:37.471298
