id: A2E5EC661
title: Prayer to Behold AmitÄbha in Dreams
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:42:37.472596
  last_modified_at: 2022-03-01 01:42:37.472599
